name: ci

on: push

jobs:
        ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.ACC_KEY }}
           aws-secret-access-key: ${{ secrets.SEC_ACC_KEY }}
           aws-region: eu-north-1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: npm ci
        env:
          CI: true
        run: |
          npm ci
      
      - name: deploy
        run: |
           npm run deploy